name: Daily Yahoo 10Y Treasury Pull

on:
  schedule:
    - cron: '0 13 * * *'  # 6:00 AM MT daily
  workflow_dispatch:

jobs:
  fetch-yield:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run scraper
        run: python get_yahoo_tnx_history.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add 10yr_yield_history.csv
          git commit -m "Update yield history on $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
